### ISSUE TITLE
`run` command doesn't work

### ISSUE THREAD

**Issue by rohit-gohri** [imfunniee/gitfolio#55]
<details>
<summary>System Information</summary>

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              | Linux                                              |
| Node Version    | v10.13.0                        |
| Project Version | 0.1.3|

</details>

<details>
<summary>What is the current behavior?</summary>
gitfolio run errors

</details>

<details>
<summary>What is the expected behavior?</summary>
Should start express server.

</details>

<details>
<summary>Logs</summary>

```sh
ctrl + c to exit
Error: ENOENT: no such file or directory, stat '/index.html'
```

</details>

The problem seems to be here:
https://github.com/imfunniee/gitfolio/blob/cbd7aeb88db9be543e2df5477c6a675fe70bd66f/run.js#L5

This should be `${outdir}/dist`

**Comment by imfunniee** [comment]
lol ye i saw that after i published the package, will patch that in next version soon. wish npm had an update command. 
For now i have written `please refrain from using this for now` so people don't use it.

**Comment by imfunniee** [comment]
fixed it 😄👍

**Comment by Hykios42** [comment]
I know this one are actually closed but the run command still not working on my side 👍 

i actually have this on my term: 
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn chrome ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

<3

**Comment by imfunniee** [comment]
@Hykios42  hmm from the error it looks like the run command is working but chrome isn't able to open up the localhost. im using this package https://www.npmjs.com/package/open

**Comment by kasvith** [comment]
> I know this one are actually closed but the run command still not working on my side +1
> 
> i actually have this on my term:
> 
> ```
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn chrome ENOENT
>     at _errnoException (util.js:1022:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
>     at onErrorNT (internal/child_process.js:372:16)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
> ```
> 
> <3

Im getting the same error on ubuntu

**Comment by kasvith** [comment]
Maybe can you do something like running a server instead of opening a web browser?

**Comment by imfunniee** [comment]
it is running a local server you can open it up on localhost:3000, i need to merge #69

**Comment by kasvith** [comment]
also add an option to change port like `-p 9090`
