### ISSUE TITLE
Order repos + forks across rows, rather than down columns ?

### ISSUE THREAD

**Issue by bcliden** [imfunniee/gitfolio#60]
# What feature should be added?
Order the repos across the rows, rather than down one column, then the other. 

# Why should this feature be added?
Presently, the second column consists of the bottom half of the repo list. This means that the top items there are very stale, making the sorting/ordering ineffective.

# Solution
I've implemented a layout with css grid that orders the repos by row, so that the sort and order methods are more effective (top of page: most starred, bottom: least starred, for example). 

Is there any interest in bringing this upstream? The repo blocks don't stack identically, as the repos all have to have a uniform height on a grid, but I do think it's an improvement. Mobile looks the same. I'll attach a screenshot below. I'm happy to make changes if a PR is in order.

of course you can also see it live here: [https://bliden.github.io/](https://bliden.github.io/)

![Screenshot_20190524_185829](https://user-images.githubusercontent.com/27828594/58360709-3a30a880-7e58-11e9-9c62-6ee3477b8af1.png)

**Comment by imfunniee** [comment]
it creates a lot of white space 🤔

**Comment by bcliden** [comment]
Yeah, I'm not super happy with it in that regard. Not sure there's a way to achieve it without introducing some js (not preferable). 

I'll take another look at it soon-- it'd be nice to have without breaking the layout. I'll close otherwise. #51 getting merged will also clean things up considerably (for me at least).

**Comment by imfunniee** [comment]
fixed #60 in PR #66

**Comment by Ironjanowar** [comment]
This bug is still happening to me in https://ironjanowar.github.io/
Am I doing something wrong? ![Here](https://github.com/Ironjanowar/ironjanowar.github.io/) is the repo if it helps.

**Comment by bcliden** [comment]
> This bug is still happening to me in https://ironjanowar.github.io/
> Am I doing something wrong? ![Here](https://github.com/Ironjanowar/ironjanowar.github.io/) is the repo if it helps.

Hi @Ironjanowar , I just pulled down a fresh copy of the master and generated your profile with 
`node ./bin/gitfolio.js build ironjanowar -s star -o desc`. Here's the build I got:
![ironjanowar_test](https://user-images.githubusercontent.com/27828594/58995622-ec566180-87c2-11e9-8ea7-9fb657a31b49.png)

I think it's a packaging issue for (paging @imfunniee) -- the npm package was last updated 10 days ago, but the PR for this one was only 6 or 7 days ago. You should try and pull down the git master and use that if you can't wait! :)

Ben
